name : Contexts
on : [push]
jobs : 
  contexts : 
    runs-on : ubuntu-latest
    env : 
      ACTOR : "${{ github.actor }}"
    steps : 
      - run : echo "${ACTOR}"
      - run : echo "${GITHUB_ACTOR}"