name : Test
on : [push]
jobs : 
  Test : 
    runs-on : ubuntu-latest
    env : 
      ACTOR : "${{ github.actor }}"
      USERNAME : "${{ vars.USERNAME }}"
      PASSWORD : "${{ secrets.PASS }}"
    steps : 
      - run : echo "${ACTOR}"
      - run : echo "${USERNAME}"
      - run : echo "${PASSWORD}"
      - run : printenv