name : TEST WORKFLOW
run-name : Run by ${{ github.actor }}
on : [push]
jobs : 
  Test : 
    name : TEST JOB
    runs-on : ubuntu-latest
    env : 
      USERNAME : "${{ vars.USERNAME }}"
      PASSWORD : "${{ secrets.PASS }}"
      FUNC_JOB : "${{ contains('test', 'st') }}"
    steps : 
      - name : SHOW MY NAME
        run : echo "${USERNAME}"
      - name : SHOW MY PASSWORD BUT NOT SHOW
        run : echo "${PASSWORD}"
      - name : FUNCTION CHECK
        run : printenv | grep 'FUNC_'
        env : 
          FUNC_STEP : "${{ contains('step', 'te') }}"
