# this is github actions workflow file
name : TEST WORKFLOW5
run-name : WORKFLOW5 RUNS BY ${{ github.actor }}
on : 
  push:
    branches : [main]
  pull_request:
    types : [opened, synchronize]
jobs : 
  job_1:
    name : JOB1
    runs-on: ubuntu-latest
    env :
      TEST : "This is a test"
    steps : 
      - name : CHECKOUT REPOSITORY
        uses : actions/checkout@v4
      - name : Check current branch
        run : echo "Current branch is ${GITHUB_HEAD_REF}"
      # - name : comment on PR
      #   run : gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}! This is a test comment."
      #   env : 
      #     GITHUB_TOKEN : "${{ secrets.GITHUB_TOKEN }}"