# this is github actions workflow file
name : TEST WORKFLOW5
run-name : WORKFLOW5 RUNS BY ${{ github.actor }}
on : 
  push:
  pull_request:
    types : [opened, synchronize]
jobs : 
  job_1:
    runs-on: ubuntu-latest
    env :
      TEST : "This is a test"
    steps : 
      - run : echo ${TEST}
      - run : printenv