name : Test
on : [push]
jobs : 
  Test : 
    runs-on : ubuntu-latest
    env : 
      ACTOR : "${{ github.actor }}"
      USERNAME : "${{ vars.USERNAME }}"
      PASSWORD : "${{ secrets.PASS }}"
      LITERAL_NULL : "{{ null }}"
      LITERAL_NUMBER : "{{ 123 }}"
      FUNC_TEST : "${{ contains('test', 'st') }}"
    steps : 
      - run : echo "${ACTOR}"
      - run : echo "${USERNAME}"
      - run : echo "${PASSWORD}"
      - run : printenv | grep 'LITERAL_'
      - run : printenv | grep 'FUNC_'
        env : 
          FUNC_STEP : "${{ contains('step', 'te') }}"
