name : TEST WORKFLOW2
run-name : Run by ${{ github.actor }}
on : [pull_request]
jobs : 
  Test : 
    name : TEST JOB2
    runs-on : ubuntu-latest
    permissions : 
      contents : read
      pull-requests: write
    env :
      GITHUB_TOKEN : "${{ secrets.GITHUB_TOKEN }}"
    steps : 
      - uses : actions/checkout@v4
      - name : COMMENT PULL REQUEST
        run : gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}! This is a test comment."
        
        
    