# this is github actions workflow file
name : TEST WORKFLOW5
run-name : WORKFLOW5 RUNS BY ${{ github.actor }}
on : [pull_request, push]
jobs : 
  job_1:
    runs-on: ubuntu-latest
    steps : 
      - run : cat /etc/os-release